# Generated by Django 4.2.7 on 2023-11-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('name', models.CharField(max_length=55)),
                ('number_of_pages', models.IntegerField(null=True)),
                ('author', models.CharField(max_length=55)),
            ],
        ),
    ]
